name: metrics

channels:
  - defaults
  - conda-forge
  - anaconda

dependencies:
  - python=3.7

  - ipykernel
  - jupyterlab
  - nb_conda_kernels

  - pandas
  - xlrd=1.2.0
  - numpy
  - matplotlib
  - seaborn
  - numba

  - openpyxl

  - black
  - flake8
